version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "6543:5432"
  ###< doctrine/doctrine-bundle ###

  www:
    build: .
    ports:
      - 8080:80
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025:1025", "1080:1080"]
###< symfony/mailer ###
